pagination:
  itemsPerPage: 22

viewer:
  videoSkipSeconds: 3

logging:
  level: info

keybinds:
  previous:
    - Digit1
  next:
    - Digit2
  close:
    - Escape
  seekBackward:
    - KeyA
  seekForward:
    - KeyS
  fitWidth:
    - KeyW
  fitHeight:
    - KeyH
  fitDefault:
    - KeyC
